<?php

/**
 * @file
 * Contains embed_youtube.module.
 */
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function embed_youtube_help($route_name, RouteMatchInterface $route_match) {
    switch ($route_name) {
        // Main module help for the embed_youtube module.
        case 'help.page.embed_youtube':
            $output = '';
            $output .= '<h3>' . t('About') . '</h3>';
            $output .= '<p>' . t('Embed youtube video to web page') . '</p>';
            return $output;

        default:
    }
}
/**
 * @implement hook_preprocess_page
 * @param type $variables
 */
function embed_youtube_preprocess_page(&$variables) {
  $variables['#attached']['library'][] = 'embed_youtube/youtube-responsive';     
}
